# Воспользуемся официальным образом для запуска python.
FROM python:3.10

# В первом контейнере необходимо будет подключение к Kafka, Redis и PostgreSQL.
# Доработайте Dockerfile, добавив в него переменные для подключения к этим сервисам.
# Расположите эти параметры между строками FROM python:3.10 и RUN apt-get update -y.

ARG CERT_PATH

ARG KAFKA_HOST
ARG KAFKA_PORT
ARG KAFKA_USER
ARG KAFKA_WORD
ARG KAFKA_GROUP
ARG KAFKA_SRC_TOPIC
ARG KAFKA_DST_TOPIC

ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_WORD

ARG BASE_HOST
ARG BASE_PORT
ARG BASE_NAME
ARG BASE_USER
ARG BASE_WORD

# Обновим компоненты в контейнере.
RUN apt-get update -y

# Копируем все файлы в контейнер.
COPY . .

# Запускаем установку зависимостей.
RUN pip install -r requirements.txt

# Устанавливаем сертификат для подключения к ресурсам в Яндекс Облаке.
RUN mkdir -p /crt
RUN wget "https://storage.yandexcloud.net/cloud-certs/CA.pem" --output-document /crt/YandexInternalRootCA.crt
RUN chmod 0600 /crt/YandexInternalRootCA.crt

# Переходим в директорию src
WORKDIR /src

# Говорим, что запускать будем python.
ENTRYPOINT ["python"]

# А именно, файл app.py в директории src.
CMD ["app.py"]